// react-evaluacion4/react-project/src/views/Navbar.jsx
import React from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';

export default function Navbar({ isLoggedIn, onLogout }) {
  const role = localStorage.getItem('role');
  const navigate = useNavigate();

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('role');
    localStorage.removeItem('userId');
    if (onLogout) onLogout();
    navigate('/');
  };

  return (
    <div className="container-fluid position-relative nav-bar p-0">
      <div className="container-lg position-relative p-0 px-lg-3" style={{ zIndex: 9 }}>
        <nav className="navbar navbar-expand-lg bg-white navbar-light shadow-lg py-3 py-lg-0 px-3">
          <Link className="navbar-brand d-flex align-items-center" to="/">
            <h1 className="m-0" style={{ fontWeight: 700, letterSpacing: 1 }}>
              <span style={{ color: '#222' }}>TRAVEL</span><span style={{ color: '#7AB730' }}>ER</span>
            </h1>
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse justify-content-end px-3" id="navbarCollapse">
            <div className="navbar-nav ml-auto py-0 d-flex align-items-center flex-lg-nowrap flex-wrap justify-content-lg-end" style={{ fontSize: '1.15rem', fontWeight: 500, gap: 24 }}>
              <NavLink to="/" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')} end>Home</NavLink>
              <NavLink to="/about" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>About</NavLink>
              <NavLink to="/service" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Services</NavLink>
              <NavLink to="/package" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Tour Packages</NavLink>
              {/* Solo admin puede ver Usuarios y Configuraciones */}
              {isLoggedIn && role === 'admin' && (
                <>
                  <NavLink to="/Usuarios" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Usuarios</NavLink>
                  <NavLink to="/Configuraciones" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Configuraciones</NavLink>
                  <NavLink to="/multimedia" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Multimedia</NavLink>
                </>
              )}
              {/* Usuarios normales solo pueden ver Usuarios si están logueados */}
              {isLoggedIn && role !== 'admin' && (
                <NavLink to="/usuarios" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Usuarios</NavLink>
              )}
              <div className="nav-item dropdown">
                <a href="#" className="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div className="dropdown-menu border-0 rounded-0 m-0">
                  <NavLink to="/blog" className="dropdown-item">Blog Grid</NavLink>
                  <NavLink to="/single" className="dropdown-item">Blog Detail</NavLink>
                  <NavLink to="/destination" className="dropdown-item">Destination</NavLink>
                  <NavLink to="/guide" className="dropdown-item">Travel Guides</NavLink>
                  <NavLink to="/testimonial" className="dropdown-item">Testimonial</NavLink>
                </div>
              </div>
              <NavLink to="/contact" className={({ isActive }) => 'nav-item nav-link' + (isActive ? ' active' : '')}>Contact</NavLink>
              {/* Botones de sesión */}
              {!isLoggedIn && (
                <>
                  <NavLink to="/login" className={({ isActive }) => 'btn btn-success ml-2' + (isActive ? ' active' : '')} style={{ minWidth: 130 }}>Iniciar Sesión</NavLink>
                  <NavLink to="/register" className={({ isActive }) => 'btn btn-outline-primary ml-2' + (isActive ? ' active' : '')} style={{ minWidth: 130 }}>Registrarse</NavLink>
                </>
              )}
              {isLoggedIn && (
                <button className="btn btn-danger ml-2" style={{ minWidth: 130 }} onClick={handleLogout}>Salir de sesión</button>
              )}
            </div>
          </div>
        </nav>
      </div>
    </div>
  );
}

// angular-evaluacion5/angular-project/src/app/components/navbar/navbar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  @Input() isLoggedIn: boolean = false;
  @Output() logout = new EventEmitter<void>();

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  get role(): string | null {
    if (typeof window !== 'undefined' && window.localStorage) {
      return localStorage.getItem('role');
    }
    return null;
  }

  handleLogout(): void {
    this.authService.logout();
    this.logout.emit();
    this.router.navigate(['/']);
  }
}

<div class="container-fluid position-relative nav-bar p-0">
  <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-lg py-3 py-lg-0 px-3">
      <a class="navbar-brand d-flex align-items-center" routerLink="/">
        <h1 class="m-0" style="font-weight: 700; letter-spacing: 1px;">
          <span style="color: #222;">TRAVEL</span><span style="color: #7AB730;">ER</span>
        </h1>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse"
        aria-controls="navbarCollapse"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end px-3" id="navbarCollapse">
        <div class="navbar-nav ml-auto py-0 d-flex align-items-center flex-lg-nowrap flex-wrap justify-content-lg-end" 
             style="font-size: 1.15rem; font-weight: 500; gap: 24px;">
          
          <a class="nav-item nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Home</a>
          <a class="nav-item nav-link" routerLink="/about" routerLinkActive="active">About</a>
          <a class="nav-item nav-link" routerLink="/service" routerLinkActive="active">Services</a>
          <a class="nav-item nav-link" routerLink="/package" routerLinkActive="active">Tour Packages</a>
          
          <!-- Solo admin puede ver Usuarios y Configuraciones -->
          @if (isLoggedIn && role === 'admin') {
            <a class="nav-item nav-link" routerLink="/usuarios" routerLinkActive="active">Usuarios</a>
            <a class="nav-item nav-link" routerLink="/configuraciones" routerLinkActive="active">Configuraciones</a>
            <a class="nav-item nav-link" routerLink="/multimedia" routerLinkActive="active">Multimedia</a>
          }
          
          <!-- Usuarios normales solo pueden ver Usuarios si están logueados -->
          @if (isLoggedIn && role !== 'admin') {
            <a class="nav-item nav-link" routerLink="/usuarios" routerLinkActive="active">Usuarios</a>
          }
          
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
            <div class="dropdown-menu border-0 rounded-0 m-0">
              <a class="dropdown-item" routerLink="/blog">Blog Grid</a>
              <a class="dropdown-item" routerLink="/single">Blog Detail</a>
              <a class="dropdown-item" routerLink="/destination">Destination</a>
              <a class="dropdown-item" routerLink="/guide">Travel Guides</a>
              <a class="dropdown-item" routerLink="/testimonial">Testimonial</a>
            </div>
          </div>
          
          <a class="nav-item nav-link" routerLink="/contact" routerLinkActive="active">Contact</a>
          
          <!-- Botones de sesión -->
          @if (!isLoggedIn) {
            <a class="btn btn-success ml-2" routerLink="/login" routerLinkActive="active" style="min-width: 130px;">Iniciar Sesión</a>
            <a class="btn btn-outline-primary ml-2" routerLink="/register" routerLinkActive="active" style="min-width: 130px;">Registrarse</a>
          }
          
          @if (isLoggedIn) {
            <button class="btn btn-danger ml-2" style="min-width: 130px;" (click)="handleLogout()">Salir de sesión</button>
          }
        </div>
      </div>
    </nav>
  </div>
</div>
