// angular-evaluacion5/angular-project/src/app/views/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  email = '';
  password = '';
  isLoading = false;

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  async handleLogin(event: Event): Promise<void> {
    event.preventDefault();
    this.isLoading = true;

    try {
      const response = await this.authService.login({ email: this.email, password: this.password }).toPromise();
      this.router.navigate(['/']);
    } catch (error: any) {
      alert(error.error?.message || 'Error al iniciar sesión');
    } finally {
      this.isLoading = false;
    }
  }
}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card p-4">
        <h2 class="mb-4 text-center">Iniciar Sesión</h2>
        <form (ngSubmit)="handleLogin($event)">
          <div class="form-group mb-3">
            <label for="email">Email</label>
            <input 
              type="email" 
              id="email"
              [(ngModel)]="email" 
              name="email"
              class="form-control" 
              required 
            />
          </div>
          <div class="form-group mb-3">
            <label for="password">Contraseña</label>
            <input 
              type="password" 
              id="password"
              [(ngModel)]="password" 
              name="password"
              class="form-control" 
              required 
            />
          </div>
          <button 
            type="submit" 
            class="btn btn-primary w-100"
            [disabled]="isLoading">
            @if (isLoading) {
              <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
              Cargando...
            } @else {
              Entrar
            }
          </button>
        </form>
        <a routerLink="/register" class="btn btn-link w-100 mt-3">¿No tienes cuenta? Regístrate</a>
      </div>
    </div>
  </div>
</div>

// react-evaluacion3/react-evaluacion3/react-project/src/views/Login.jsx
import React, { useState } from 'react';
import { login } from '../api';
import { useNavigate, Link } from 'react-router-dom';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const response = await login({ email, password });
      localStorage.setItem('token', response.token);
      localStorage.setItem('role', response.role);
      localStorage.setItem('userId', response.id);
      navigate('/');
    } catch (error) {
      alert(error.response?.data?.message || 'Error al iniciar sesión');
    }
  };

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card p-4">
            <h2 className="mb-4 text-center">Iniciar Sesión</h2>
            <form onSubmit={handleLogin}>
              <div className="form-group">
                <label>Email</label>
                <input type="email" value={email} onChange={e => setEmail(e.target.value)} className="form-control" required />
              </div>
              <div className="form-group">
                <label>Contraseña</label>
                <input type="password" value={password} onChange={e => setPassword(e.target.value)} className="form-control" required />
              </div>
              <button type="submit" className="btn btn-primary w-100">Entrar</button>
            </form>
            <Link to="/register" className="btn btn-link w-100 mt-3">¿No tienes cuenta? Regístrate</Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
