// angular-evaluacion5/angular-project/src/app/views/package/package.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-package',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './package.component.html',
  styleUrl: './package.component.css'
})
export class PackageComponent {
}

<div class="container-fluid py-5">
  <div class="container py-5">
    <div class="text-center mb-5">
      <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Paquetes</h6>
      <h1 class="display-4 mb-4">Paquetes de Viaje</h1>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="package-item bg-white rounded shadow-sm">
          <div class="package-img">
            <img class="img-fluid" src="assets/package-1.jpg" alt="Package" style="width: 100%; height: 200px; object-fit: cover;">
          </div>
          <div class="p-4">
            <div class="d-flex justify-content-between mb-2">
              <small class="m-0"><i class="fa fa-map-marker-alt text-primary me-2"></i>Thailand</small>
              <small class="m-0"><i class="fa fa-calendar-alt text-primary me-2"></i>3 días</small>
            </div>
            <h5 class="mb-3">Discover amazing places of the world with us</h5>
            <div class="d-flex justify-content-between">
              <div class="d-flex align-items-center">
                <small class="m-0"><i class="fa fa-star text-primary"></i></small>
                <small class="m-0 ms-1">4.5</small>
                <small class="m-0 ms-1">(250)</small>
              </div>
              <div class="d-flex align-items-center">
                <small class="m-0"><i class="fa fa-users text-primary me-2"></i>2</small>
              </div>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <h5 class="m-0 text-primary">$350</h5>
              <a class="btn btn-primary" href="#">Ver Detalles</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// react-evaluacion3/react-evaluacion3/react-project/src/views/Package.jsx
import React from 'react';
import package1 from '../assets/package-1.jpg';
import package2 from '../assets/package-2.jpg';
import package3 from '../assets/package-3.jpg';
import package4 from '../assets/package-4.jpg';
import package5 from '../assets/package-5.jpg';
import package6 from '../assets/package-6.jpg';
import { Link } from 'react-router-dom';

const packages = [
  { img: package1, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
  { img: package2, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
  { img: package3, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
  { img: package4, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
  { img: package5, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
  { img: package6, country: 'Thailand', days: 3, people: 2, title: 'Discover amazing places of the world with us', rating: 4.5, reviews: 250, price: 350 },
];

const Package = () => (
  <>
    {/* Header Start */}
    <div className="container-fluid page-header">
      <div className="container">
        <div className="d-flex flex-column align-items-center justify-content-center" style={{ minHeight: 400 }}>
          <h3 className="display-4 text-white text-uppercase">Packages</h3>
          <div className="d-inline-flex text-white">
            <Link className="text-white" to="/">Home</Link>
            <i className="fa fa-angle-double-right pt-1 px-3"></i>
            <span className="m-0 text-uppercase">Packages</span>
          </div>
        </div>
      </div>
    </div>
    {/* Header End */}

    {/* Booking Start */}
    <div className="container-fluid booking mt-5 pb-5">
      <div className="container pb-5">
        <div className="bg-light shadow" style={{ padding: 30 }}>
          <div className="row align-items-center" style={{ minHeight: 60 }}>
            <div className="col-md-10">
              <div className="row">
                <div className="col-md-3">
                  <div className="mb-3 mb-md-0">
                    <select className="custom-select px-4" style={{ height: 47 }}>
                      <option defaultValue>Destination</option>
                      <option value="1">Destination 1</option>
                      <option value="2">Destination 2</option>
                      <option value="3">Destination 3</option>
                    </select>
                  </div>
                </div>
                <div className="col-md-3">
                  <div className="mb-3 mb-md-0">
                    <div className="date" id="date1" data-target-input="nearest">
                      <input type="text" className="form-control p-4 datetimepicker-input" placeholder="Depart Date" data-target="#date1" data-toggle="datetimepicker" />
                    </div>
                  </div>
                </div>
                <div className="col-md-3">
                  <div className="mb-3 mb-md-0">
                    <div className="date" id="date2" data-target-input="nearest">
                      <input type="text" className="form-control p-4 datetimepicker-input" placeholder="Return Date" data-target="#date2" data-toggle="datetimepicker" />
                    </div>
                  </div>
                </div>
                <div className="col-md-3">
                  <div className="mb-3 mb-md-0">
                    <select className="custom-select px-4" style={{ height: 47 }}>
                      <option defaultValue>Duration</option>
                      <option value="1">Duration 1</option>
                      <option value="2">Duration 2</option>
                      <option value="3">Duration 3</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-2">
              <button className="btn btn-primary btn-block" type="submit" style={{ height: 47, marginTop: -2 }}>Submit</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* Booking End */}

    {/* Packages Start */}
    <div className="container-fluid py-5">
      <div className="container pt-5 pb-3">
        <div className="text-center mb-3 pb-3">
          <h6 className="text-primary text-uppercase" style={{ letterSpacing: 5 }}>Packages</h6>
          <h1>Pefect Tour Packages</h1>
        </div>
        <div className="row">
          {packages.map((pkg, i) => (
            <div className="col-lg-4 col-md-6 mb-4" key={i}>
              <div className="package-item bg-white mb-2">
                <img className="img-fluid" src={pkg.img} alt="package" />
                <div className="p-4">
                  <div className="d-flex justify-content-between mb-3">
                    <small className="m-0"><i className="fa fa-map-marker-alt text-primary mr-2"></i>{pkg.country}</small>
                    <small className="m-0"><i className="fa fa-calendar-alt text-primary mr-2"></i>{pkg.days} days</small>
                    <small className="m-0"><i className="fa fa-user text-primary mr-2"></i>{pkg.people} Person</small>
                  </div>
                  <a className="h5 text-decoration-none" href="#">{pkg.title}</a>
                  <div className="border-top mt-4 pt-4">
                    <div className="d-flex justify-content-between">
                      <h6 className="m-0"><i className="fa fa-star text-primary mr-2"></i>{pkg.rating} <small>({pkg.reviews})</small></h6>
                      <h5 className="m-0">${pkg.price}</h5>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
    {/* Packages End */}
  </>
);

export default Package;
