// angular-evaluacion5/angular-project/src/app/views/register/register.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {
  email = '';
  password = '';
  confirmPassword = '';
  nombre = '';
  telefono = '';
  direccion = '';
  fechaNacimiento = '';
  isLoading = false;
  errors: any = {};

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  validateForm(): boolean {
    this.errors = {};
    
    // Validar email
    if (!this.email) {
      this.errors.email = 'El email es requerido';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.email)) {
      this.errors.email = 'El email no es válido';
    }
    
    // Validar contraseña
    if (!this.password) {
      this.errors.password = 'La contraseña es requerida';
    } else if (this.password.length < 6) {
      this.errors.password = 'La contraseña debe tener al menos 6 caracteres';
    }
    
    // Validar confirmación de contraseña
    if (!this.confirmPassword) {
      this.errors.confirmPassword = 'La confirmación de contraseña es requerida';
    } else if (this.password !== this.confirmPassword) {
      this.errors.confirmPassword = 'Las contraseñas no coinciden';
    }

    // Validar nombre
    if (!this.nombre) {
      this.errors.nombre = 'El nombre es requerido';
    }

    return Object.keys(this.errors).length === 0;
  }

  async handleRegister(event: Event): Promise<void> {
    event.preventDefault();
    
    if (!this.validateForm()) {
      return;
    }

    this.isLoading = true;

    try {
      await this.authService.register({
        nombre: this.nombre,
        email: this.email,
        password: this.password,
        telefono: this.telefono,
        direccion: this.direccion,
        fecha_nacimiento: this.fechaNacimiento
      }).toPromise();
      
      alert('Registro exitoso. Ahora puedes iniciar sesión.');
      this.router.navigate(['/login']);
    } catch (error: any) {
      alert(error.error?.message || 'Error en el registro');
    } finally {
      this.isLoading = false;
    }
  }
}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card p-4">
        <h2 class="mb-4 text-center">Registrarse</h2>
        <form (ngSubmit)="handleRegister($event)">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="nombre">Nombre Completo</label>
                <input 
                  type="text" 
                  id="nombre"
                  [(ngModel)]="nombre" 
                  name="nombre"
                  class="form-control" 
                  [class.is-invalid]="errors.nombre"
                  required 
                />
                @if (errors.nombre) {
                  <div class="invalid-feedback">{{ errors.nombre }}</div>
                }
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="email">Email</label>
                <input 
                  type="email" 
                  id="email"
                  [(ngModel)]="email" 
                  name="email"
                  class="form-control" 
                  [class.is-invalid]="errors.email"
                  required 
                />
                @if (errors.email) {
                  <div class="invalid-feedback">{{ errors.email }}</div>
                }
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="telefono">Teléfono</label>
                <input 
                  type="tel" 
                  id="telefono"
                  [(ngModel)]="telefono" 
                  name="telefono"
                  class="form-control" 
                />
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="fechaNacimiento">Fecha de Nacimiento</label>
                <input 
                  type="date" 
                  id="fechaNacimiento"
                  [(ngModel)]="fechaNacimiento" 
                  name="fechaNacimiento"
                  class="form-control" 
                />
              </div>
            </div>
          </div>

          <div class="form-group mb-3">
            <label for="direccion">Dirección</label>
            <textarea 
              id="direccion"
              [(ngModel)]="direccion" 
              name="direccion"
              class="form-control" 
              rows="3"
            ></textarea>
          </div>

          <div class="row">
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="password">Contraseña</label>
                <input 
                  type="password" 
                  id="password"
                  [(ngModel)]="password" 
                  name="password"
                  class="form-control" 
                  [class.is-invalid]="errors.password"
                  required 
                />
                @if (errors.password) {
                  <div class="invalid-feedback">{{ errors.password }}</div>
                }
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group mb-3">
                <label for="confirmPassword">Confirmar Contraseña</label>
                <input 
                  type="password" 
                  id="confirmPassword"
                  [(ngModel)]="confirmPassword" 
                  name="confirmPassword"
                  class="form-control" 
                  [class.is-invalid]="errors.confirmPassword"
                  required 
                />
                @if (errors.confirmPassword) {
                  <div class="invalid-feedback">{{ errors.confirmPassword }}</div>
                }
              </div>
            </div>
          </div>

          <button 
            type="submit" 
            class="btn btn-primary w-100"
            [disabled]="isLoading">
            @if (isLoading) {
              <span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
              Registrando...
            } @else {
              Registrarse
            }
          </button>
        </form>
        <a routerLink="/login" class="btn btn-link w-100 mt-3">¿Ya tienes cuenta? Inicia sesión</a>
      </div>
    </div>
  </div>
</div>

// react-evaluacion3/react-evaluacion3/react-project/src/views/Register.jsx
import React, { useState } from 'react';
import { register } from '../api';
import { useNavigate, Link } from 'react-router-dom';
import { validations } from '../utils/validations';

const Register = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const navigate = useNavigate();

  const [errors, setErrors] = useState({});

  const validateForm = () => {
    const newErrors = {};
    
    // Validar email
    const emailError = validations.email(email);
    if (emailError) newErrors.email = emailError;
    
    // Validar contraseña
    const passwordError = validations.password(password);
    if (passwordError) newErrors.password = passwordError;
    
    // Validar confirmación de contraseña
    const confirmPasswordError = validations.confirmPassword(password, confirmPassword);
    if (confirmPasswordError) newErrors.confirmPassword = confirmPasswordError;

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleRegister = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    try {
      await register({
        email,
        password,
        confirmPassword
      });
      alert('Registro exitoso. Ahora puedes iniciar sesión.');
      navigate('/login');
    } catch (error) {
      alert(error.response?.data?.message || 'Error en el registro');
    }
  };

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card p-4">
            <h2 className="mb-4 text-center">Registro</h2>
            <form onSubmit={handleRegister}>
              <div className="form-group">
                <label>Email</label>
                <input 
                  type="email" 
                  value={email} 
                  onChange={e => setEmail(e.target.value)} 
                  className={`form-control ${errors.email ? 'is-invalid' : ''}`} 
                  required 
                />
                {errors.email && <div className="invalid-feedback">{errors.email}</div>}
              </div>
              <div className="form-group">
                <label>Contraseña</label>
                <input 
                  type="password" 
                  value={password} 
                  onChange={e => setPassword(e.target.value)} 
                  className={`form-control ${errors.password ? 'is-invalid' : ''}`} 
                  required 
                />
                {errors.password && <div className="invalid-feedback">{errors.password}</div>}
              </div>
              <div className="form-group">
                <label>Confirmar Contraseña</label>
                <input 
                  type="password" 
                  value={confirmPassword} 
                  onChange={e => setConfirmPassword(e.target.value)} 
                  className={`form-control ${errors.confirmPassword ? 'is-invalid' : ''}`} 
                  required 
                />
                {errors.confirmPassword && <div className="invalid-feedback">{errors.confirmPassword}</div>}
              </div>
              <button type="submit" className="btn btn-success w-100">Registrarse</button>
            </form>
            <Link to="/login" className="btn btn-link w-100 mt-3">¿Ya tienes cuenta? Inicia sesión</Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
